[package]
name = "nlp_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = "0.36.2"
rayon = "1.8.1"
regex = "1.10.3"
stopwords = "0.1.1"
